sever {
    listen 8080;
    root ./www;
    index index.html;

    location / {
        methods GET DELETE ;
    }

    location /images {
        root ./www/images;
        methods GET ;
    }

    location /old {
        return 301 /new;
    }
}
