server { 
    listen 0;#port range is 1-65535
    root ./www; #serve file from(comments are ignored in parsing)
    index index.html;

    location / {
        methods GET DELETE ;
    }

    location /images {
        root ./www/images;
        methods GET ;
    }

    location /old {
        return 301 /new;
    }
}