server {                                                                                                                                                                                                                                                                                                           
    listen 127.0.0.1:8080;
    root ./www;
    index index.html;

    location / {
        methods GET DELETE ;
    }
}


server {                                                                                                                                                                                                                                                                                                           
    listen 127.0.0.1:8080;
    root ./www;
    index test9090.html;

    location / {
        methods GET DELETE ;
    }
}