server {
    listen 8080;
    root ./www;
    index index.html;

    location / {
        methods GET;
    }
}

server {
    listen 127.0.0.1:9090;
    root ./www2;
    index index.html;

    location / {
        methods GET;
    }
}